language: node_js
node_js:
  - '9'
script:
  - npx eslint .
  - npm test
after_success:
  -  if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
     export AUTH0_SECRET=$AUTH0_SECRET_STAGING;
     export API_URL=$API_URL_STAGING;
     export TELEGRAM_TOKEN=$TELEGRAM_TOKEN_STAGING;
     npx serverless deploy --conceal;
     fi

  -  if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "production" ]; then
     export AUTH0_SECRET=$AUTH0_SECRET_PROD;
     export API_URL=$API_URL_PROD;
     export TELEGRAM_TOKEN=$TELEGRAM_TOKEN_PROD;
     npx serverless deploy --conceal -v -s prod;
     fi
